<#
SCENARIO:
An AVD team needs a daily session host report to give service desk staff a quick view of host
health across the AVD host pool. A data export from Azure has been saved as a JSON file
(06.TASK-DATA.json). The team wants a CSV collating the key fields: the VM name (not the full
resource path), Status, Sessions, MaxSessionLimit, AllowNewSession, AssignedUser, and a formatted
LastHeartBeat timestamp.

A first implementation has been written that reads the file and builds the CSV rows. It works for
some hosts, but the data export is not always complete — some fields may be missing — and the
script does not account for this. Run the script as-is first and observe what happens.

In a real world scenario, the JSON file would likely be generated by an API call (e.g. Microsoft Graph)
or pipeline step, and the CSV would be consumed by a service desk tool or automation — so data 
quality is important, and the script needs to be robust against incomplete data.

TASK:
Fix the script so it handles incomplete data gracefully. There are two categories of problem to
address, each requiring a different approach:

1. Some missing values should cause a clear warning message and a placeholder value inserted
     instead — the service desk still needs a complete report, but also needs to know when data
     quality is poor. Add a validation check that logs a warning and inserts a placeholder in the CSV.

2. Some operations will throw an unhandled exception depending on the data, halting the entire
     loop so later hosts are never processed. Wrap the risky operation so a single bad record is
     caught and reported, without stopping the rest of the run.

WHY IT MATTERS:
1. Silent failures are dangerous: code that runs without errors but produces incomplete output is
     harder to detect than a crash. A blank Status column in a service desk report looks like a
     mistake, not an alert — and may never get noticed. In other scenarios, a missing value could
     cause a downstream process to fail in a more critical way, such as a patching script that skips
     important hosts because they were not in the report.
2. Unhandled exceptions stop everything: without protection, a single host with missing data halts the
     run entirely and all subsequent hosts are missing from the report.
3. Choosing the right pattern matters: not every problem needs a try/catch, and not every problem
     needs a validation guard — knowing which to reach for is the skill.

Task guidance
TODO 1: Identify where null/empty values lead to misleading CSV data. Add validation that writes
            a warning and substitutes a placeholder value in the output row.
TODO 2: Identify the risky operation that can throw and stop processing. Add try/catch handling
            so one bad record does not halt the entire run.
#>

$JsonPath  = '.\01_PowerShell\06.TASK-DATA.json'
$CsvPath   = '.\01_PowerShell\session-host-report.csv'

$SessionHosts = Get-Content -Path $JsonPath -Raw | ConvertFrom-Json

$CsvRows = @()

foreach ($SessionHost in $SessionHosts) {

     $ParsedHeartbeat = [DateTime]::Parse($SessionHost.LastHeartBeat)

     $Row = [PSCustomObject]@{
          HostName        = $SessionHost.Name.Split('/')[1]
          Status          = $SessionHost.Status
          Sessions        = $SessionHost.Sessions
          MaxSessionLimit = $SessionHost.MaxSessionLimit
          AllowNewSession = $SessionHost.AllowNewSession
          AssignedUser    = $SessionHost.AssignedUser
          LastHeartBeat   = $ParsedHeartbeat.ToString('dd/MM/yyyy HH:mm')
     }

     $CsvRows += $Row
}

$CsvRows | Export-Csv -Path $CsvPath -NoTypeInformation -Encoding UTF8
Write-Output "Report written to $CsvPath"
