<#
SCENARIO:
You now need to build a script from scratch rather than refactor an existing one. An AVD team wants
an exception report from the session host JSON export (06.TASK-DATA.json) created in the previous task.
Specifically, they need the name of every host that is not in an Available state, along with the
AssignedUser for that host, so support teams can quickly identify hosts that may need intervention.

In a real world scenario, the JSON file would likely be generated by an API call (e.g. Microsoft Graph)
or pipeline step, and the output would be consumed by a service desk tool or automation — so data
quality is important, and the script needs to be robust against incomplete data.

TASK:
Create a script that accepts the JSON file path as a parameter, reads the data, and outputs hosts where
Status is anything other than Available. The script must use a parameterised function to do the filter
logic, and must include validation and error handling. There should be no null values, any issues should
be clearly logged, and the output should be clear and actionable for support teams. Additionally, include
Write-Host statements at each major step to provide clear feedback on the script's progress and any issues
encountered.

WHY IT MATTERS:
1. Build-from-scratch scripting is a different skill from refactoring and is common in automation work.
2. Parameterised scripts and functions are reusable in pipelines and scheduled jobs.
3. Validation catches bad inputs early and avoids wasted runs.
4. Error handling keeps failures clear and actionable for operators.
5. Clear output is essential for downstream consumers, such as service desk staff.
6. Write-Host feedback improves the user experience and helps with troubleshooting when things go wrong.

Task guidance
TODO 1: Add a script parameter for the input JSON path (for example, $JsonPath).
        (to simplify for this task, this can be a parameter with a default value, rather than a
        mandatory parameter that must be provided at runtime).
TODO 2: Validate the parameter value (file exists, and is not empty).
TODO 3: Get and convert the JSON (within a try/catch), to an object with clear error output if
        parsing fails.
TODO 4: Create a parameterised function that accepts the HostData.
TODO 5: In the function, return only hosts where Status is not Available (case-insensitive), and
        include at least HostName, Status and AssignedUser in the output.
TODO 6: Add validation inside the function for required properties and handle missing values safely.
TODO 7: Use Write-Host at each major step (start, validation passed, parsing complete, filtering,
        summary) and include warnings/errors when issues are found.
TODO 8: Output a clear final result (objects are fine) and a summary count.
#>

# Build the full solution below using the requirements above.
