name: LnD-GHA-Task05-Template

on:
  workflow_call:
    inputs:
      env:
        description: 'The deployment environment (e.g., dev, staging, prod)'
        required: true
        type: string
      version:
        description: 'The version of the application to deploy'
        required: true
        type: string

permissions:
  contents: read

jobs:
  task05:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Task 05 Script
        shell: pwsh
        run: |
          .\05_GitHubActions\gha_scripts\05deployScript.ps1 -Environment "${{ inputs.env }}" -Version "${{ inputs.version }}" -Application "${{ vars.APP_NAME }}"