name: LnD-GHA-Task05-Caller

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the application to deploy'
        required: true
        default: '1.0.0'
      environment:
        description: 'The environment to deploy to (e.g., dev, staging, prod)'
        required: true
        default: 'dev'

permissions:
  contents: read

jobs:
  call_task05:
    uses: ./.github/workflows/06-task05-template.yml
    with:
      version: ${{ inputs.version }}
      env: ${{ inputs.environment }}