name: LnD-GHA-Task05-Caller

on:
  workflow_dispatch:
    inputs:
      # TODO: Define the inputs for the caller workflow
      # - env         (choice: dev / prod)
      # - version     (string - the version number or tag being deployed)

permissions:
  contents: read

jobs:
  call_task05:
    # TODO: Call the template workflow at ./.github/workflows/06-task05-template.yml
    # TODO: Pass the workflow inputs through to the template
